server:
  port: 9021
spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/zuul_auth?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: 103305
      druid:
        driver-class-name:  com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis:
  mapper-locations: classpath:mapper/*.xml